# Copyright (C) 2023 Mitsubishi Electric Research Laboratories (MERL)
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: bansac
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - h5py
  - matplotlib
  - gcc
  - tqdm
  - pandas
  - tabulate
  - pre-commit
  - black==22.12.0
  - flake8
